# Generated by Django 6.0.3 on 2026-03-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сборки')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('purpose', models.CharField(blank=True, max_length=50, verbose_name='Назначение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(related_name='popular_builds', to='products.product')),
            ],
        ),
    ]
