# Generated by Django 6.0.3 on 2026-03-20 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('preferred_time', models.CharField(blank=True, max_length=100, verbose_name='Предпочтительное время')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('assigned', 'Назначен мастер'), ('in_progress', 'Выехал'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('assigned_master', models.CharField(blank=True, max_length=100, verbose_name='Назначенный мастер')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий сотрудника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100, verbose_name='Тип устройства')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Предпочтительная дата')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('diagnostic', 'Диагностика'), ('waiting_parts', 'Ожидание запчастей'), ('repair', 'Ремонт'), ('completed', 'Готов к выдаче'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий сотрудника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
